# Generated by Django 5.2.7 on 2025-10-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this question is active (not soft deleted)'),
        ),
        migrations.AddField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this section is active (not soft deleted)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Incremented when survey is edited'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey_version',
            field=models.PositiveIntegerField(default=1, help_text='Version of survey when response was submitted'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this user profile is active (not soft deleted)'),
        ),
    ]
